import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../ui/Navbar";
import Footer from "@/ui/Footer";

export const metadata: Metadata = {
  title: "Felipe Leite Mantovani",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="bg-[var(--bg-light)] w-full h-full flex flex-col justify-between">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
